name: Node CI
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [build]
  workflow_dispatch:
jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build static site
        run: npm run build
      - name: Deploy site to GitHub Pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: "build"
          GH_PAT: ${{ secrets.GH_PAT }}
